apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- patch: |-
- op: replace
  path: /metadata/labels/app
  value: dev-rhel9-vm
- op: replace
  path: /metadata/name
  value: dev-rhel9-vm
- op: replace
  path: spec/template/metadata/labels/kubevirt.io/domain
  value: dev-rhel9-vm
- op: replace
  path: spec/template/spec/domain/devices/disks/name
  value: dev-rhel9-vm-rootdisk
